### ISSUE TITLE
No content?

### ISSUE THREAD

**Issue by ethanfree23** [learn-co-curriculum/welcome-to-algorithms-and-data-structures-inperson#1]
### Canvas Link

https://learning.flatironschool.com/courses/4570

### Concern

I do not see any content to study? Nor an export content option. Please advise.

**Comment by lizbur10** [comment]
Hi @ethanfree23 ! Thanks for bringing this to our attention - the problem should now be resolved, so I'm going to close this issue. Please re-open it if you are still unable to access the content.

Cheers 💙
