### ISSUE TITLE
empty?

### ISSUE THREAD

**Issue by DannaEWaltz** [learn-co-curriculum/welcome-to-algorithms-and-data-structures-inperson#2]
### Canvas Link

https://learning.flatironschool.com/courses/5211

### Concern

Hiya, love the idea -- where's the content?

### Additional Context

n/a

### Suggested Changes

Would love something inside this algorithms & data structures learning curriculum

**Comment by lizbur10** [comment]
Hi @DannaEWaltz ! You can access the content by clicking "Modules" in the nav on the let. I also added this info to the home page. Thanks for contributing to the Flatiron School curriculum 💙
